#ifndef _COMMON_h_
#define _COMMON_h_
#include "types.h"
#include "A7129.h"
#include "A7139_CONFIG.h"
#include "board.h"
#include "digio.h"
#include "defs.h"
#include "int.h"
#include "delay.h"
#include "led.h"
#include <msp430.h>
#include <stdio.h>
#include "spi.h"
#include "mcu.h"
#include "sys.h"
#include "timer.h"
#include "uart.h"
#include "in430.h"
#include "trsdata.h"
#include "interrupt.h"
#include "scan.h"
#include "TaskQ.h"
#endif